### ISSUE TITLE
crash when try to solve 

### ISSUE THREAD

**Issue by muhammadarif1** [anjaneya2b/KinematicEquationSolver#2]
android 5.1

```FATAL EXCEPTION: main
Process: com.anjaneya2bgmail.kinematics, PID: 4206
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.anjaneya2bgmail.kinematics.f.onClick()
	at android.view.View.performClick(View.java:4848)
	at android.view.View$PerformClick.run(View.java:20299)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by muhammadarif1** [comment]
Please feedbcak sir
